### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by jasonwynn10** [LostTeam/LostSounds#6]
- [ ] Wait for release of mcpe add-ons
- [ ] Create packet for custom sounds
- [ ] Scan resource directory for sound files
  - [ ] mp3
  - [ ] wav
  - [ ] flac
  - [ ] aa
  - [ ] m4a
- [ ] Add customizable settings in config file

**Comment by thelucyclub** [comment]
You have your add-ons!
